//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuRequest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeuDesignation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NeuDesignation()
        {
            this.NueUserOrgMapper = new HashSet<NueUserOrgMapper>();
            this.NueUserProfile = new HashSet<NueUserProfile>();
            this.NueUserProfile1 = new HashSet<NueUserProfile>();
        }
    
        public int Id { get; set; }
        public string Desig { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueUserOrgMapper> NueUserOrgMapper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueUserProfile> NueUserProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueUserProfile> NueUserProfile1 { get; set; }
    }
}
