//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuRequest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NueUserOrgMapper
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OrgUserId { get; set; }
        public Nullable<int> OrgUserType { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        public virtual NeuDesignation NeuDesignation { get; set; }
        public virtual NueUserProfile NueUserProfile { get; set; }
        public virtual NueUserProfile NueUserProfile1 { get; set; }
    }
}
