//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuRequest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NeuUserPreference
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> IsMailCommunication { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> FirstApprover { get; set; }
        public Nullable<int> SecondApprover { get; set; }
    
        public virtual NueUserProfile NueUserProfile { get; set; }
        public virtual NueUserProfile NueUserProfile1 { get; set; }
        public virtual NueUserProfile NueUserProfile2 { get; set; }
    }
}
