//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuRequest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NueRequestAttachmentLog
    {
        public int Id { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string Request { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public string VFileName { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual NueUserProfile NueUserProfile { get; set; }
        public virtual NueRequestMaster NueRequestMaster { get; set; }
        public virtual NueUserProfile NueUserProfile1 { get; set; }
    }
}
