//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Req
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NueRequestEntities : DbContext
    {
        public NueRequestEntities()
            : base("name=NueRequestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Designation> Designation { get; set; }
        public virtual DbSet<EmployeeVerificationRequest> EmployeeVerificationRequest { get; set; }
        public virtual DbSet<EmploymentStatus> EmploymentStatus { get; set; }
        public virtual DbSet<JobLevel> JobLevel { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<NeuUserPreference> NeuUserPreference { get; set; }
        public virtual DbSet<NueAccessMapper> NueAccessMapper { get; set; }
        public virtual DbSet<NueAccessMaster> NueAccessMaster { get; set; }
        public virtual DbSet<NueAddressProofRequest> NueAddressProofRequest { get; set; }
        public virtual DbSet<NueDomesticTripRequest> NueDomesticTripRequest { get; set; }
        public virtual DbSet<NueGeneralRequest> NueGeneralRequest { get; set; }
        public virtual DbSet<NueInternationalTripRequest> NueInternationalTripRequest { get; set; }
        public virtual DbSet<NueLeaveBalanceEnquiryRequest> NueLeaveBalanceEnquiryRequest { get; set; }
        public virtual DbSet<NueLeaveCancelationRequest> NueLeaveCancelationRequest { get; set; }
        public virtual DbSet<NueLeavePastApplyRequest> NueLeavePastApplyRequest { get; set; }
        public virtual DbSet<NueLeaveWFHApplyRequest> NueLeaveWFHApplyRequest { get; set; }
        public virtual DbSet<NueManagerMapper> NueManagerMapper { get; set; }
        public virtual DbSet<NueRequestAceessLog> NueRequestAceessLog { get; set; }
        public virtual DbSet<NueRequestActivity> NueRequestActivity { get; set; }
        public virtual DbSet<NueRequestActivityMaster> NueRequestActivityMaster { get; set; }
        public virtual DbSet<NueRequestAttachmentLog> NueRequestAttachmentLog { get; set; }
        public virtual DbSet<NueRequestMaster> NueRequestMaster { get; set; }
        public virtual DbSet<NueRequestStatus> NueRequestStatus { get; set; }
        public virtual DbSet<NueRequestSubType> NueRequestSubType { get; set; }
        public virtual DbSet<NueRequestType> NueRequestType { get; set; }
        public virtual DbSet<NueSalaryCertificateRequest> NueSalaryCertificateRequest { get; set; }
        public virtual DbSet<NueUserOrgMapper> NueUserOrgMapper { get; set; }
        public virtual DbSet<NueUserProfile> NueUserProfile { get; set; }
        public virtual DbSet<Practice> Practice { get; set; }
        public virtual DbSet<UserDetail> UserDetail { get; set; }
    }
}
