//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Req
{
    using System;
    using System.Collections.Generic;
    
    public partial class NueAccessMapper
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> AccessId { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        public virtual NueAccessMaster NueAccessMaster { get; set; }
        public virtual NueUserProfile NueUserProfile { get; set; }
    }
}
