//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Req
{
    using System;
    using System.Collections.Generic;
    
    public partial class NueRequestMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NueRequestMaster()
        {
            this.NueRequestAceessLog = new HashSet<NueRequestAceessLog>();
            this.NueRequestActivity = new HashSet<NueRequestActivity>();
            this.NueRequestAttachmentLog = new HashSet<NueRequestAttachmentLog>();
        }
    
        public int Id { get; set; }
        public string RequestId { get; set; }
        public Nullable<int> IsApprovalProcess { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<int> PayloadId { get; set; }
        public Nullable<int> RequestCatType { get; set; }
        public System.DateTime AddedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestAceessLog> NueRequestAceessLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestActivity> NueRequestActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestAttachmentLog> NueRequestAttachmentLog { get; set; }
        public virtual NueUserProfile NueUserProfile { get; set; }
        public virtual NueRequestStatus NueRequestStatus { get; set; }
        public virtual NueRequestSubType NueRequestSubType { get; set; }
    }
}
