//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Req
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NueRequestEntities1 : DbContext
    {
        public NueRequestEntities1()
            : base("name=NueRequestEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NeuDesignation> NeuDesignation { get; set; }
        public virtual DbSet<NeuEmployeeVerificationRequest> NeuEmployeeVerificationRequest { get; set; }
        public virtual DbSet<NeuEmploymentStatus> NeuEmploymentStatus { get; set; }
        public virtual DbSet<NeuJobLevel> NeuJobLevel { get; set; }
        public virtual DbSet<NeuMessages> NeuMessages { get; set; }
        public virtual DbSet<NeuPractice> NeuPractice { get; set; }
        public virtual DbSet<NeuUserDetail> NeuUserDetail { get; set; }
        public virtual DbSet<NeuUserPreference> NeuUserPreference { get; set; }
        public virtual DbSet<NueAccessMapper> NueAccessMapper { get; set; }
        public virtual DbSet<NueAccessMaster> NueAccessMaster { get; set; }
        public virtual DbSet<NueAddressProofRequest> NueAddressProofRequest { get; set; }
        public virtual DbSet<NueDBLocationChangeRequest> NueDBLocationChangeRequest { get; set; }
        public virtual DbSet<NueDBManagerChangeRequest> NueDBManagerChangeRequest { get; set; }
        public virtual DbSet<NueDomesticTripRequest> NueDomesticTripRequest { get; set; }
        public virtual DbSet<NueGeneralRequest> NueGeneralRequest { get; set; }
        public virtual DbSet<NueInternationalTripRequest> NueInternationalTripRequest { get; set; }
        public virtual DbSet<NueLeaveBalanceEnquiryRequest> NueLeaveBalanceEnquiryRequest { get; set; }
        public virtual DbSet<NueLeaveCancelationRequest> NueLeaveCancelationRequest { get; set; }
        public virtual DbSet<NueLeavePastApplyRequest> NueLeavePastApplyRequest { get; set; }
        public virtual DbSet<NueLeaveWFHApplyRequest> NueLeaveWFHApplyRequest { get; set; }
        public virtual DbSet<NueManagerMapper> NueManagerMapper { get; set; }
        public virtual DbSet<NueRequestAceessLog> NueRequestAceessLog { get; set; }
        public virtual DbSet<NueRequestActivity> NueRequestActivity { get; set; }
        public virtual DbSet<NueRequestActivityMaster> NueRequestActivityMaster { get; set; }
        public virtual DbSet<NueRequestAttachmentLog> NueRequestAttachmentLog { get; set; }
        public virtual DbSet<NueRequestMaster> NueRequestMaster { get; set; }
        public virtual DbSet<NueRequestStatus> NueRequestStatus { get; set; }
        public virtual DbSet<NueRequestSubType> NueRequestSubType { get; set; }
        public virtual DbSet<NueRequestType> NueRequestType { get; set; }
        public virtual DbSet<NueSalaryCertificateRequest> NueSalaryCertificateRequest { get; set; }
        public virtual DbSet<NueUserOrgMapper> NueUserOrgMapper { get; set; }
        public virtual DbSet<NueUserProfile> NueUserProfile { get; set; }
    }
}
