//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Req
{
    using System;
    using System.Collections.Generic;
    
    public partial class NueRequestSubType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NueRequestSubType()
        {
            this.NueRequestMaster = new HashSet<NueRequestMaster>();
        }
    
        public int Id { get; set; }
        public string RequestSubType { get; set; }
        public Nullable<int> RequestType { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestMaster> NueRequestMaster { get; set; }
        public virtual NueRequestType NueRequestType { get; set; }
    }
}
