//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Req
{
    using System;
    using System.Collections.Generic;
    
    public partial class NueRequestActivityMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NueRequestActivityMaster()
        {
            this.NueRequestActivity = new HashSet<NueRequestActivity>();
        }
    
        public int Id { get; set; }
        public string ActivityDesc { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestActivity> NueRequestActivity { get; set; }
    }
}
