//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeuRequest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NueUserProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NueUserProfile()
        {
            this.NeuEmployeeVerificationRequest = new HashSet<NeuEmployeeVerificationRequest>();
            this.NeuMessages = new HashSet<NeuMessages>();
            this.NeuUserPreference = new HashSet<NeuUserPreference>();
            this.NeuUserPreference1 = new HashSet<NeuUserPreference>();
            this.NeuUserPreference2 = new HashSet<NeuUserPreference>();
            this.NueAccessMapper = new HashSet<NueAccessMapper>();
            this.NueAddressProofRequest = new HashSet<NueAddressProofRequest>();
            this.NueDomesticTripRequest = new HashSet<NueDomesticTripRequest>();
            this.NueGeneralRequest = new HashSet<NueGeneralRequest>();
            this.NueInternationalTripRequest = new HashSet<NueInternationalTripRequest>();
            this.NueLeaveBalanceEnquiryRequest = new HashSet<NueLeaveBalanceEnquiryRequest>();
            this.NueLeaveCancelationRequest = new HashSet<NueLeaveCancelationRequest>();
            this.NueLeavePastApplyRequest = new HashSet<NueLeavePastApplyRequest>();
            this.NueLeaveWFHApplyRequest = new HashSet<NueLeaveWFHApplyRequest>();
            this.NueManagerMapper = new HashSet<NueManagerMapper>();
            this.NueManagerMapper1 = new HashSet<NueManagerMapper>();
            this.NueRequestAceessLog = new HashSet<NueRequestAceessLog>();
            this.NueRequestAceessLog1 = new HashSet<NueRequestAceessLog>();
            this.NueRequestActivity = new HashSet<NueRequestActivity>();
            this.NueRequestAttachmentLog = new HashSet<NueRequestAttachmentLog>();
            this.NueRequestAttachmentLog1 = new HashSet<NueRequestAttachmentLog>();
            this.NueRequestMaster = new HashSet<NueRequestMaster>();
            this.NueSalaryCertificateRequest = new HashSet<NueSalaryCertificateRequest>();
            this.NueUserOrgMapper = new HashSet<NueUserOrgMapper>();
            this.NueUserOrgMapper1 = new HashSet<NueUserOrgMapper>();
        }
    
        public int Id { get; set; }
        public string NTPLID { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> EmploymentStatus { get; set; }
        public string DateofJoining { get; set; }
        public Nullable<int> Practice { get; set; }
        public string Location { get; set; }
        public Nullable<int> JobLevel { get; set; }
        public Nullable<int> Designation { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> AddedOn { get; set; }
    
        public virtual NeuDesignation NeuDesignation { get; set; }
        public virtual NeuDesignation NeuDesignation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NeuEmployeeVerificationRequest> NeuEmployeeVerificationRequest { get; set; }
        public virtual NeuEmploymentStatus NeuEmploymentStatus { get; set; }
        public virtual NeuEmploymentStatus NeuEmploymentStatus1 { get; set; }
        public virtual NeuJobLevel NeuJobLevel { get; set; }
        public virtual NeuJobLevel NeuJobLevel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NeuMessages> NeuMessages { get; set; }
        public virtual NeuPractice NeuPractice { get; set; }
        public virtual NeuPractice NeuPractice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NeuUserPreference> NeuUserPreference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NeuUserPreference> NeuUserPreference1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NeuUserPreference> NeuUserPreference2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueAccessMapper> NueAccessMapper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueAddressProofRequest> NueAddressProofRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueDomesticTripRequest> NueDomesticTripRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueGeneralRequest> NueGeneralRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueInternationalTripRequest> NueInternationalTripRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueLeaveBalanceEnquiryRequest> NueLeaveBalanceEnquiryRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueLeaveCancelationRequest> NueLeaveCancelationRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueLeavePastApplyRequest> NueLeavePastApplyRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueLeaveWFHApplyRequest> NueLeaveWFHApplyRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueManagerMapper> NueManagerMapper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueManagerMapper> NueManagerMapper1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestAceessLog> NueRequestAceessLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestAceessLog> NueRequestAceessLog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestActivity> NueRequestActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestAttachmentLog> NueRequestAttachmentLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestAttachmentLog> NueRequestAttachmentLog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueRequestMaster> NueRequestMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueSalaryCertificateRequest> NueSalaryCertificateRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueUserOrgMapper> NueUserOrgMapper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NueUserOrgMapper> NueUserOrgMapper1 { get; set; }
    }
}
